<?php

declare(strict_types=1);

namespace Ttskch\UserBundle\Controller\Registration;

use Doctrine\ORM\EntityManagerInterface;
use Psr\EventDispatcher\EventDispatcherInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;

class RegisterController extends AbstractController
{
    /**
     * @var EntityManagerInterface
     */
    private $em;

    /**
     * @var EventDispatcherInterface
     */
    private $eventDispatcher;

    /**
     * @var string
     */
    private $userClassName;

    /**
     * @var string
     */
    private $formTypeClassName;

    public function __construct(EntityManagerInterface $em, EventDispatcherInterface $eventDispatcher, string $userClassName, string $formTypeClassName)
    {
        $this->em = $em;
        $this->eventDispatcher = $eventDispatcher;
        $this->userClassName = $userClassName;
        $this->formTypeClassName = $formTypeClassName;
    }

    public function __invoke(Request $request)
    {
        if ($this->isGranted('IS_AUTHENTICATED_REMEMBERED')) {
            return $this->redirectToRoute('ttskch_user_profile_show');
        }

        $user = new $this->userClassName();

        $form = $this->createForm($this->formTypeClassName, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            if ($form->isValid()) {
                $this->em->persist($user);
                $this->em->flush();

                // todo: earn response which generated by EventListener like as FOSUserBundle is doing
                // if (! $response = $event->getResponse()) {
                //     $response = $this->redirectToRoute('ttskch_user_registration_confirmed');
                // }
                $response = $this->redirectToRoute('ttskch_user_registration_confirmed');

                // todo: dispatch some event like REGISTRATION_SUCCESS here

                return $response;
            }

            // todo: dispatch some event like REGISTRATION_FAILURE here

            // todo: earn response which generated by EventListener like as FOSUserBundle is doing
            // if ($response = $event->getResponse()) {
            //     return $response;
            // }
        }

        return $this->render('@!TtskchUser/Registration/register.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}
